CREATE TABLE IF NOT EXISTS exists_on (
  q_code TEXT NOT NULL,
  domain TEXT NOT NULL,
  PRIMARY KEY (q_code,domain),
) 

ALTER TABLE exists_on
  ADD CONSTRAINT fk10 FOREIGN KEY (q_code) REFERENCES question (q_code) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT fk11 FOREIGN KEY (domain) REFERENCES online_judge (domain) ON DELETE CASCADE ON UPDATE CASCADE;