CREATE TABLE IF NOT EXISTS solution_of (
  s_id INTEGER NOT NULL PRIMARY KEY,
  q_code TEXT NOT NULL,
  
);

ALTER TABLE solution_of
  ADD CONSTRAINT fk5 FOREIGN KEY (s_id) REFERENCES solution (s_id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT fk6 FOREIGN KEY (q_code) REFERENCES question (q_code) ON DELETE CASCADE ON UPDATE CASCADE;


