CREATE TABLE IF NOT EXISTS submits (
  s_id INTEGER NOT NULL PRIMARY KEY,
  username TEXT NOT NULL,
  );

ALTER TABLE submits
  ADD CONSTRAINT fk3 FOREIGN KEY (s_id) REFERENCES solution(s_id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT fk4 FOREIGN KEY (username) REFERENCES person (username) ON DELETE CASCADE ON UPDATE CASCADE;


