CREATE TABLE IF NOT EXISTS adds
(
	q_code INTEGER NOT NULL,
	username TEXT NOT NULL,
	FOREIGN KEY (q_code) REFERENCES question (q_code) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (username) REFERENCES user (username) ON DELETE CASCADE ON UPDATE CASCADE
);
