CREATE TABLE IF NOT EXISTS solution_of
(
	s_id INTEGER NOT NULL PRIMARY KEY,
	q_code INTEGER NOT NULL,
	FOREIGN KEY (s_id) REFERENCES solution (s_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (q_code) REFERENCES question (q_code) ON DELETE CASCADE ON UPDATE CASCADE
);


