CREATE TABLE IF NOT EXISTS submits
(
	s_id INTEGER NOT NULL PRIMARY KEY,
	username TEXT NOT NULL,
	FOREIGN KEY (s_id) REFERENCES solution(s_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (username) REFERENCES user (username) ON DELETE CASCADE ON UPDATE CASCADE
);




