CREATE TABLE IF NOT EXISTS writes
(
	q_code TEXT PRIMARY KEY NOT NULL,
	username TEXT NOT NULL,
	FOREIGN KEY (q_code) REFERENCES question (q_code) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (username) REFERENCES person (username) ON DELETE CASCADE ON UPDATE CASCADE
);
